import Head from "next/head";
import Link from "next/link";
import Header from "../components/Header";
import Layout from "../components/Layout/layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Header></Header>
      </Head>
      <Layout>
        <section>MAIN</section>
      </Layout>
    </>
  );
}
